language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - yarn
  - yarn global add coveralls
script:
  - jest --coverage --coverageReporters=text-lcov | coveralls
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs/
  target_branch: gh-pages
  verbose: true
  on:
    branch: master
