language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - yarn
  - yarn global add coveralls
script:
  - jest --coverage --coverageReporters=text-lcov | coveralls
